/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.Contato;
import model.banco;

/**
 *
 * @author Natan de Paula
 * @author Eriani Moreira
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrinciopalView
     */
    public PrincipalView() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        opcoesJmenu = new javax.swing.JMenu();
        jmenuNovo = new javax.swing.JMenuItem();
        jMenuListar = new javax.swing.JMenuItem();
        jMenuFechar = new javax.swing.JMenuItem();
        janelaJmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcoesJmenu.setText("Opções");

        jmenuNovo.setText("Novo contato");
        jmenuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuNovoActionPerformed(evt);
            }
        });
        opcoesJmenu.add(jmenuNovo);

        jMenuListar.setText("Listar contatos");
        jMenuListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarActionPerformed(evt);
            }
        });
        opcoesJmenu.add(jMenuListar);

        jMenuFechar.setText("Fechar o sistema");
        jMenuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFecharActionPerformed(evt);
            }
        });
        opcoesJmenu.add(jMenuFechar);

        jMenuBar1.add(opcoesJmenu);

        janelaJmenu.setText("Janela");
        jMenuBar1.add(janelaJmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuNovoActionPerformed
        Pessoa novo = new Pessoa();
        novo.setVisible(true);
       
        
    }//GEN-LAST:event_jmenuNovoActionPerformed

    private void jMenuListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListarActionPerformed
      ListaContatos lista= new ListaContatos();
      lista.setVisible(true);
     // DefaultTableModel dtmContatos = (DefaultTableModel) tabela.getModel();
    }//GEN-LAST:event_jMenuListarActionPerformed

    private void jMenuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFecharActionPerformed
       this.dispose();
    }//GEN-LAST:event_jMenuFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuFechar;
    private javax.swing.JMenuItem jMenuListar;
    private javax.swing.JMenu janelaJmenu;
    private javax.swing.JMenuItem jmenuNovo;
    private javax.swing.JMenu opcoesJmenu;
    // End of variables declaration//GEN-END:variables
}
